### ISSUE TITLE
Crypto Chest

### ISSUE THREAD

**Issue by Emir236070** [polymerdevs/Quest-Into-The-Polyverse-Phase-1#47]
Hello, this project is a gamified treasure raffle event.

**Gameplay Mechanics:** There are 15 boxes in the game (these boxes can be increased or decreased), these boxes are hidden with rewards in a completely random way (the number of rewards and winnings can be changed), including NFT rewards*, there are 3 keys (the number of keys can be increased), these boxes are used to open the chests Can be used for. You open it, you only have 3 rights.

**User Settings:** Each user is allowed to play only once; This event can be used to reward users who are eligible to win prizes.

repository of codes: https://github.com/Emir236070/crypto-chest/

**Comment by kenobijon** [comment]
Hey please submit this in the comments of the New Ideas issue! Great Idea though
